language: python

python:
 
  - "2.7"
  
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  
# command to install dependencies
install:
  - pip install flask_restful

  - pip install python-coveralls
  - pip install coverage
  - pip install -r requirements.txt
  - pip install green

script:
  
  - nosetests --with-coverage
  - python test_api.py
  
 
after_success:
  - coveralls