language: python

python:
 - "3.6"
  
# command to install dependencies
install:
  - "pip install -r requirements.txt"
 
script: 

  #- python test_api.py
  - nosetests --with-coverage --cover-erase --cover-package=api/ && coverage repor
 
 after_success:
  - "coveralls"